jenkins:

    build: ./
    dockerfile: Dockerfile
    container_name: jenkins-master

    ports:
        - "8080:8080"
        - 50000:50000

    volumes_from:
        - jenkins-data

jenkins-data:

    build: ./
    dockerfile: Dockerfile-data
    container_name: jenkins-data